<option value="">Select Category</option> 
<option value="business_entrepreneurship">Business & Entrepreneurship</option>
<option value="technology_innovation">Technology & Innovation</option>
<option value="funding_and_grants">Funding & Grants</option>
<option value="arts_entertainment">Arts & Entertainment</option>
<option value="education_learning">Education & Learning</option>
<option value="health_wellness">Health & Wellness</option>
<option value="environment_sustainability">Environment & Sustainability</option>
<option value="science_research">Science & Research</option>
<option value="social_impact_community">Social Impact & Community</option>
<option value="sports_fitness">Sports & Fitness</option>
<option value="travel_adventure">Travel & Adventure</option>
<option value="volunteer_charity">Volunteer & Charity</option>
<option value="career_job_opportunities">Career & Job Opportunities</option>
<option value="networking_conferences">Networking & Conferences</option>
<option value="workshops_training">Workshops & Training</option>
<option value="competitions_contests">Competitions & Contests</option>
<option value="cultural_heritage">Cultural & Heritage</option>
<option value="food_culinary">Food & Culinary</option>
<option value="fashion_beauty">Fashion & Beauty</option>
<option value="personal_development">Personal Development</option>
<option value="virtual_online_events">Virtual & Online Events</option>
<option value="music_concerts">Music & Concerts</option>
<option value="literature_writing">Literature & Writing</option>
<option value="film_media">Film & Media</option>
<option value="gaming_esports">Gaming & Esports</option>
<option value="government">Government</option>
<option value="philanthropy_fundraising">Philanthropy & Fundraising</option>