    <option value="">Select Country</option> 
    <option value="algeria">Algeria</option>
    <option value="angola">Angola</option>
    <option value="benin">Benin</option>
    <option value="botswana">Botswana</option>
    <option value="burkina_faso">Burkina Faso</option>
    <option value="burundi">Burundi</option>
    <option value="cape_verde">Cape Verde</option>
    <option value="cameroon">Cameroon</option>
    <option value="central_african_republic">Central African Republic</option>
    <option value="chad">Chad</option>
    <option value="comoros">Comoros</option>
    <option value="congo_brazzaville">Congo (Brazzaville)</option>
    <option value="congo_kinshasa">Congo (Kinshasa)</option>
    <option value="djibouti">Djibouti</option>
    <option value="egypt">Egypt</option>
    <option value="equatorial_guinea">Equatorial Guinea</option>
    <option value="eritrea">Eritrea</option>
    <option value="eswatini">Eswatini</option>
    <option value="ethiopia">Ethiopia</option>
    <option value="gabon">Gabon</option>
    <option value="gambia">Gambia</option>
    <option value="ghana">Ghana</option>
    <option value="guinea">Guinea</option>
    <option value="guinea_bissau">Guinea-Bissau</option>
    <option value="ivory_coast">Ivory Coast</option>
    <option value="kenya">Kenya</option>
    <option value="lesotho">Lesotho</option>
    <option value="liberia">Liberia</option>
    <option value="libya">Libya</option>
    <option value="madagascar">Madagascar</option>
    <option value="malawi">Malawi</option>
    <option value="mali">Mali</option>
    <option value="mauritania">Mauritania</option>
    <option value="mauritius">Mauritius</option>
    <option value="morocco">Morocco</option>
    <option value="mozambique">Mozambique</option>
    <option value="namibia">Namibia</option>
    <option value="niger">Niger</option>
    <option value="nigeria">Nigeria</option>
    <option value="rwanda">Rwanda</option>
    <option value="sao_tome_and_principe">Sao Tome and Principe</option>
    <option value="senegal">Senegal</option>
    <option value="seychelles">Seychelles</option>
    <option value="sierra_leone">Sierra Leone</option>
    <option value="somalia">Somalia</option>
    <option value="south_africa">South Africa</option>
    <option value="south_sudan">South Sudan</option>
    <option value="sudan">Sudan</option>
    <option value="tanzania">Tanzania</option>
    <option value="togo">Togo</option>
    <option value="tunisia">Tunisia</option>
    <option value="uganda">Uganda</option>
    <option value="zambia">Zambia</option>
    <option value="zimbabwe">Zimbabwe</option>
  