name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Server
      env:
        HOST_NAME: ${{ secrets.HOST_NAME }}
        USER_NAME: ${{ secrets.USER_NAME }}
        USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
        TARGET_DIR: ${{ secrets.TARGET_DIR }}
      run: |
        scp -r \
        -o StrictHostKeyChecking=no \
        -o UserKnownHostsFile=/dev/null \
        . $USER_NAME@$HOST_NAME:$TARGET_DIR
        ssh $USER_NAME@$HOST_NAME "
          cd $TARGET_DIR
          composer install --no-interaction --no-dev --prefer-dist
        "
